---
- name: Setup systemd unit file path and systemctl scope variables determined by user
  ansible.builtin.set_fact:
    systemd_unit_path: '{{ "/etc/systemd/system" if ansible_user_id == "root" else ansible_env.HOME + "/.config/systemd/user" }}'
    systemctl_scope: '{{ "system" if ansible_user_id == "root" else "user" }}'
- name: Ensure application work directory exist
  ansible.builtin.file:
    path: /opt/{{ app_work_directory }}
    state: directory
    mode: '0755'
- name: Update application service unit file
  ansible.builtin.template:
    src: hello.service.j2
    dest: '{{ systemd_unit_path }}/{{ app_name }}.service'
    mode: '0644'
- name: Upload new application executable file
  ansible.builtin.copy:
    src: '{{ local_artifact }}'
    dest: /opt/{{ app_work_directory }}/app.jar
    mode: '0755'
    force: true
- name: Systemd daemon reload and start application service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ app_name }}.service'
    state: restarted
    enabled: true
    scope: '{{ systemctl_scope }}'
- name: Wait for application to be ready
  ansible.builtin.wait_for:
    port: '{{ app_port }}'
    delay: 13
    timeout: 23
    msg: 'Application is not ready'
